### ISSUE TITLE
React.js app has CORS issue

### ISSUE THREAD

**Issue by rgraham7503** [IBM-Security/verify-sdk-javascript#17]
Access to fetch at 'https://mytenant.ice.ibmcloud.com/v1.0/authenticators' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Tried multiple cors plugins none have worked. I have reached the conclusion that a proxy would need to be used. (example: https://daveceddia.com/access-control-allow-origin-cors-errors-in-react-express/)
If you can’t modify the server, you can run your own proxy. And this proxy can return the Access-Control-Allow-Origin header if it’s not at the Same Origin as your page.

Instead of sending API requests to some remote server, you’ll make requests to your proxy, which will forward them to the remote server. Here are a few proxy options.

**Comment by trumanbutter** [comment]
@rgraham7503, As you're probably already aware CI does support CORS. You can read more about how to implement this in the knowledge centre. https://www-03preprod.ibm.com/support/knowledgecenter/SSCT62_dev/com.ibm.iamservice.doc/tasks/domains.html
