### ISSUE TITLE
React Sample from IBM Security Verify Developer portal not working

### ISSUE THREAD

**Issue by timothydilbert** [IBM-Security/verify-sdk-javascript#74]
# Overview
The React sample application available for download after creating an App in the IBM Security Verify Developer portal does not work. It is throwing the following error:
```
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```
Full screenshot is below:

![image](https://user-images.githubusercontent.com/79225033/151083981-b6d319f0-e0bc-4bee-8a96-0a7a09cbe4f2.png)

# Steps to reproduce
1. Open the Developer Portal.
2. Through the wizard, create a new application with the following settings:
a) Grant Type: Implicit
b) Grant Type settings: http://localhost:3000 (for both the `App URL` and `Redirect URL`
3. Download the React Sample app.
4. Run the code using according to the documentation outlined in Github:
https://github.com/IBM-Security/verify-sdk-javascript/tree/master/samples/implicit-flow/react
5. Open http://localhost:3000 and receive the abovementioned error.

**Comment by devenIBM** [comment]
Same issue happening.
